dependencies:
  - name: randori-service
    version: 1.0.0
    repository: https://cerqueiraedu.github.io/aikido-app-charts/charts/randori-service
  - name: atemi-service
    version: 1.0.0
    repository: https://cerqueiraedu.github.io/aikido-app-charts/charts/atemi-service/
  - name: technique-service
    version: 1.0.0
    repository: https://cerqueiraedu.github.io/aikido-app-charts/charts/technique-service