dependencies:
  - name: aikido-randori-service
    version: 1.0.0
    repository: https://cerqueiraedu.github.io/aikido-app-charts/charts/aikido-randori-service
  - name: aikido-atemi-service
    version: 1.0.0
    repository: https://cerqueiraedu.github.io/aikido-app-charts/charts/aikido-atemi-service/
  - name: aikido-technique-service
    version: 1.0.0
    repository: https://cerqueiraedu.github.io/aikido-app-charts/charts/aikido-technique-service/